server.port: 8080


spring:
  application.name: skateshop
  data:
    mongodb:
      host: localhost
      port: 27017
      database: flip
      username: mongoadmin
      password: secret
      authentication-database: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: flip.skateshop.noreply@gmail.com
    password: dummy-smtp-password-1234
    properties.mail:
      transport.protocol: smtp
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

skateshop:
  security:
    jwt:
      secret-key: devSecretKeyForJwtTokenMustBeAtLeast32BytesLong!
      token-validity-in-seconds: 9999999999
    verification-key:
      validity-in-seconds: 180

  minio:
    access-key: minioadmin
    bucket: flip
    endpoint: http://localhost:9000
    secret-key: password

logging:
  level:
    web: DEBUG
