POST http://localhost:8080/auth/reset-password/send/user@example.com


###
POST http://localhost:8080/auth/reset-password
Content-Type: application/json

{
  "email": "user@example.com",
  "newPassword": "test",
  "verificationKey": "ntJRym"
}
